export const MOBILE_OPEN = 'MOBILE_OPEN'
export const MOBILE_CLOSE = 'MOBILE_CLOSE'
export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'

export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const SORT_PRODUCTS = 'SORT_PRODUCTS'
export const UPDATE_SORT = 'UPDATE_SORT'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'
export const UPDATE_FILTERS = 'UPDATE_FILTERS'

export const PATH_UPDATE = 'PATH_UPDATE'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const PATH_TEST = 'PATH_TEST'

export const GET_SINGLE_PRODUCT_BEGIN = 'GET_SINGLE_PRODUCT_BEGIN'
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS'
export const GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLE_PRODUCT_ERROR'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_CART_PRODUCT = 'REMOVE_CART_PRODUCT'
export const TOGGLE_CART_PRODUCT_AMOUNT = 'TOGGLE_CART_PRODUCT_AMOUNT'
export const CLEAR_CART = 'CEAR_CART'
export const COUNT_CART_TOTALS = 'COUNT_CART_TOTALS'