export const MOBILE_OPEN = 'MOBILE_OPEN'
export const MOBILE_CLOSE = 'MOBILE_CLOSE'
export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'

export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const SORT_PRODUCTS = 'SORT_PRODUCTS'
export const UPDATE_SORT = 'UPDATE_SORT'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'
export const UPDATE_FILTERS = 'UPDATE_FILTERS'

export const PATH_UPDATE = 'PATH_UPDATE'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'


export const PATH_TEST = 'PATH_TEST'